/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MenuImport } from './routes/menu'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ProfileIndexLazyImport = createFileRoute('/profile/')()
const OrdersIndexLazyImport = createFileRoute('/orders/')()
const LoginIndexLazyImport = createFileRoute('/login/')()
const CartIndexLazyImport = createFileRoute('/cart/')()

// Create/Update Routes

const MenuRoute = MenuImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexLazyRoute = ProfileIndexLazyImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile/index.lazy').then((d) => d.Route))

const OrdersIndexLazyRoute = OrdersIndexLazyImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/orders/index.lazy').then((d) => d.Route))

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const CartIndexLazyRoute = CartIndexLazyImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cart/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuImport
      parentRoute: typeof rootRoute
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/cart': typeof CartIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/orders': typeof OrdersIndexLazyRoute
  '/profile': typeof ProfileIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/cart': typeof CartIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/orders': typeof OrdersIndexLazyRoute
  '/profile': typeof ProfileIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/cart/': typeof CartIndexLazyRoute
  '/login/': typeof LoginIndexLazyRoute
  '/orders/': typeof OrdersIndexLazyRoute
  '/profile/': typeof ProfileIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/menu' | '/cart' | '/login' | '/orders' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/menu' | '/cart' | '/login' | '/orders' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/menu'
    | '/cart/'
    | '/login/'
    | '/orders/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenuRoute: typeof MenuRoute
  CartIndexLazyRoute: typeof CartIndexLazyRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
  OrdersIndexLazyRoute: typeof OrdersIndexLazyRoute
  ProfileIndexLazyRoute: typeof ProfileIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuRoute: MenuRoute,
  CartIndexLazyRoute: CartIndexLazyRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
  OrdersIndexLazyRoute: OrdersIndexLazyRoute,
  ProfileIndexLazyRoute: ProfileIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/menu",
        "/cart/",
        "/login/",
        "/orders/",
        "/profile/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/menu": {
      "filePath": "menu.tsx"
    },
    "/cart/": {
      "filePath": "cart/index.lazy.tsx"
    },
    "/login/": {
      "filePath": "login/index.lazy.tsx"
    },
    "/orders/": {
      "filePath": "orders/index.lazy.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
